### ISSUE TITLE
Add IDF version for IDF file

### ISSUE THREAD

**Issue by michaldengusiak** [ladybug-tools/honeybee-energy#104]
Could we add IDF version into IDF file you produce?

![image](https://user-images.githubusercontent.com/26113670/75869878-1f855a00-5e02-11ea-8bca-727bd118a8f5.png)

![image](https://user-images.githubusercontent.com/26113670/75869842-14cac500-5e02-11ea-9a41-2a71b8372f43.png)

**Comment by chriswmackey** [comment]
The first half of this issue is done in that the honeybee_energy.config has a property to track the installed version of EnergyPlus/OpenStudio:
https://github.com/ladybug-tools/honeybee-energy/pull/105

There's also now a method to generate the IDF version string.  At this point, we just need to make use of this code in honeybee-energy-grasshopper components and then we should be done here.

**Comment by chriswmackey** [comment]
This is now all addressed via https://github.com/ladybug-tools/honeybee-grasshopper-energy/pull/26
