### ISSUE TITLE
HourlyContinuousCollections for zone heating and cooling load from ZSZ class have incorrect(?) analysis period. 

### ISSUE THREAD

**Issue by saeranv** [ladybug-tools/honeybee-energy#646]
@chriswmackey 

I've been working with the 'HB Read Zone Sizing' component and have noticed that the cooling_load_data and heating_load_data collections both are hardcoded with an analysis period of January 1st, which I've tracked back to this line: 

https://github.com/ladybug-tools/honeybee-energy/blob/fee59fcee125ecfe02d295e42a2afa71759c1e91/honeybee_energy/result/zsz.py#L59

Shouldn't this reflect the design day month and day?

**Comment by chriswmackey** [comment]
Yes, this is a known bug and thanks for opening the GitHub issue for it. [As you can see from my response on the forum](https://discourse.ladybug.tools/t/stacked-data-lb-monthly-chart-does-not-get-stacked/12219/7?u=chris), I don't really know how I am going to solve it, since the zsz file doesn't contain any information about the date of the design day.

I can at least say that the results out of the new "HB Peak Loads" Grasshopper component have the correct date because I know what the design days are before the simulation gets executed.

The only option that I can see here is to expose some optional arguments on `__init__` to set the dates of the cooling/heating design day if they are known from a source outside of the `zsz` file. If you have any other suggestions or there is something that I missed when looking at the zsz file, let me know.

**Comment by saeranv** [comment]
@chriswmackey 

That makes sense, thanks for clarifying it, and sorry for my late response here. 

I agree with you that I don't think there is a better option from the zsz file.  I can't think of a way to retrieve specific design day information from just the file. 

Personally, I think opening up the optional arguments on `__init__` and the component would be useful. Not only would it give an easy way for people to modify the dates, which is useful when constructing graphs, but also alerts people to the fact that the default dates are not reflective of the actual design days. Alternatively, adding a comment to the output that clarifies the dates are hardcoded to 1/1 would also work.
