### ISSUE TITLE
Example file tolerance error

### ISSUE THREAD

**Issue by visualizor** [ladybug-tools/honeybee-energy#816]
the `shoe_box_energy_model` example file for honeybee-energy gave me tolerance errors, likely caused by geometry created infinitesimally close to origin point. 
This is the component that raised the error.
![image](https://user-images.githubusercontent.com/25107288/149556386-17b58ba5-6518-4d66-8b14-7310e48c8ffb.png)

It's solved by moving the internalized "shoebox" geometries away from 0,0,0

**Comment by mostaphaRoudsari** [comment]
Hi @visualizor! Thank you for reporting the issue. You should post this comment to the Ladybug Tools forum: https://discourse.ladybug.tools

It will also be helpful if you can copy the exact error message that you received. Having the room next to the origin should not cause any issues. Are you sure your model units weren't in mm? That can become an issue since our input values in Grasshopper are in meters and you might have created a very tiny room.
