### ISSUE TITLE
RoomEnergyProperties set program_type warning / notification?

### ISSUE THREAD

**Issue by PH-Tools** [ladybug-tools/honeybee-energy#927]
Hi @chriswmackey 

I just ran into a small item that seemed to be a bit counterintuitive, and wondering if there might be an easy fix?

# Scenario:
If the user has previously set any of the [RoomEnergyProperties](https://github.com/ladybug-tools/honeybee-energy/blob/dba36ebb0274fbb88d8b0f134e9d997757d0c092/honeybee_energy/properties/room.py#L45) attributes such as ventilation, people, etc.. and then tries to set the [program_type](https://github.com/ladybug-tools/honeybee-energy/blob/dba36ebb0274fbb88d8b0f134e9d997757d0c092/honeybee_energy/properties/room.py#L132), those custom attributes get preserved, but without any notification or warning to the user that this is happening?

For instance, if I have a simple scene like this, where I first set a custom load, and then later set the program-type: that custom load sticks around on the room:
<img width="1673" alt="image" src="https://user-images.githubusercontent.com/69652712/213753862-4302c10c-1d1c-4917-9445-b1f2fd74f451.png">

# Possible Solution 1:
To me, this is a bit counter intuitive / unexpected? I would expect the [Apply Program Type](https://github.com/ladybug-tools/honeybee-grasshopper-energy/blob/master/honeybee_grasshopper_energy/src/HB%20Apply%20ProgramType.py) component to reset all the loads and schedules for the room, overwriting any previously set attributes/loads/schedules? So that would be (I think?) just resetting all the specific program attributes on the `RoomEnergyProperties` to `None` whenever the `program_type` is set.

# Possible Solution 2:
Or: if you think its really important to preserve those custom-set loads, then perhaps just something as simple as a component user-warning/notification that "Hey: your Room has custom loads that were NOT reset by the Apply Program Type" or something like that?
<img width="1022" alt="image" src="https://user-images.githubusercontent.com/69652712/213757567-8c295692-11f1-4199-bc85-20be7c13549f.png">

[set_program_example.gh.zip](https://github.com/ladybug-tools/honeybee-energy/files/10468285/set_program_example.gh.zip)

**Comment by mostaphaRoudsari** [comment]
@PH-Tools,

Thank you for documenting this. I don't know what @chriswmackey would say but I think the plugin is working as expected. We don't re-write the values that are assigned by the user. The program type is there as a backup to get the values when they are not set. The values don't overwrite the template itself, they just take precedent over the values that are provided by template. That's why between the two suggestions I would vote for solution 2.

**Comment by chriswmackey** [comment]
Hey @PH-Tools ,

@mostaphaRoudsari summarized my thoughts well. It doesn't really seem that counter-intuitive from the perspective of the schema or structure of Honeybee models. Most of us would have inferred that values assigned to individual rooms will override the ProgramType just like constructions assigned to individual Faces override the ConstructionSet. However, I can see how it might be a little confusing form the perspective of your visual script there. For that reason, I feel that anything that we implement to ameliorate this should be primarily on the Grasshopper end and not change things in the core libraries. Meaning that your Option 2 is much better than Option 1 in my mind.

I have not yet used the "HB Apply Program Type" component in my own scripts and I had imagined that, if I were ever to use it, it would be before any component that overwrote the loads of individual rooms. So I could see how nudging users to consider the structure of honeybee models and ordering their components accordingly could be helpful. Can you talk more about the scenarios where you have found yourself using the "HB Apply Program Type" component? This may help me understand if one solution is preferred over another.

FYI, another thing that we can do is add a component that resets all of the Room properties to the default, essentially erasing any existing properties so that you can start fresh. [We already have a method for this on honeybee rooms](https://www.ladybug.tools/honeybee-energy/docs/honeybee_energy.properties.room.html#honeybee_energy.properties.room.RoomEnergyProperties.reset_to_default) and we can expand it to also clear all constructions that are overridden on individual faces.

**Comment by PH-Tools** [comment]
Hi @chriswmackey 

To give some more background: the specific use case this popped up in was in a 'variants' testing scenario: ie, a building model was all created and defined (sometimes with those room-level assignments) and then we were testing some 'global' modifications to the attribute/program values to evaluate impact (which was done at the end of the script, right before calculation). So yes in that case we were taking a highly defined model and trying to make program-level modifications in a later step, expecting them all to overwrite any existing attributes.

But I agree: once you know the rules and what to expect from that component it makes sense. So it think that this could be clarified by just adding a note to the component description, or a user-flag / warning / info-note so that it is clear that any room-level assignments do not get reset  / overwritten by that component?

**Comment by chriswmackey** [comment]
FYI, @PH-Tools . I just implemented some methods that assist with checking Rooms for overridden loads and can reset all of the loads to be from the program type:

https://github.com/ladybug-tools/honeybee-energy/pull/980

Before the end of today, I will make use of these methods on the "Apply Program Type" component to essentially implement both proposed solutions. Essentially, users will get a warning if there are overridden loads and I'll implement a new option on the component that can overwrite them if it is set to True.
